version: '3.4'

services:
  familyscoreboard:
    image: ${DOCKER_REGISTRY-}familyscoreboard
    build:
      context: .
      dockerfile: FamilyScoreboard\Dockerfile
  ui:
    image: ${DOCKER_REGISTRY-}ui
    build:
      context: .
      dockerfile: UI\Dockerfile
