// <auto-generated />
using System;
using FamilyScoreboard.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FamilyScoreboard.Migrations
{
    [DbContext(typeof(ScoreboardContext))]
    [Migration("20200204171506_initializedatabase")]
    partial class initializedatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("FamilyScoreboard.Models.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PointValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Chores");
                });

            modelBuilder.Entity("FamilyScoreboard.Models.CompletedChore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DateEntered")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FamilyMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("FamilyMemberId");

                    b.ToTable("CompletedChores");
                });

            modelBuilder.Entity("FamilyScoreboard.Models.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FamilyMemebers");
                });

            modelBuilder.Entity("FamilyScoreboard.Models.CompletedChore", b =>
                {
                    b.HasOne("FamilyScoreboard.Models.Chore", "Chore")
                        .WithMany()
                        .HasForeignKey("ChoreId");

                    b.HasOne("FamilyScoreboard.Models.FamilyMember", "FamilyMember")
                        .WithMany("CompletedChores")
                        .HasForeignKey("FamilyMemberId");
                });
#pragma warning restore 612, 618
        }
    }
}
